### ISSUE TITLE
add level fun

### ISSUE THREAD

**Issue by Amalgamatte** [c-128/TheBackroomsExperiment#3]
it is
it is about adding the level fun i think.
![image](https://user-images.githubusercontent.com/108957198/228642642-7d5a6716-1fd5-477c-9b6c-2a8d260f2da9.png)

this is. the picture :).

entrance is from 1117 89 1254 in repeating rooms

exit from floor 3 of this level can lead you to aperture laboratories, otherwise you get to colorful vents

**Comment by Amalgamatte** [comment]
> ok where is repeating rooms and the other sublevels, we'd need to document those first

made an issue bout that too

**Comment by c-128** [comment]
Done with all exits
