### ISSUE TITLE
add level colorful vents

### ISSUE THREAD

**Issue by Amalgamatte** [c-128/TheBackroomsExperiment#6]
colorful vents :)
no photo :(

level 5 entrance to the colorful vents: 10 314
 level 4 entrance to the colorful vents: -879 -1218
 you can also get there from level fun :)

**Comment by c-128** [comment]
oh there we go

**Comment by c-128** [comment]
https://github.com/c-128/TheBackroomsExperiment/blob/master/wiki/sublevels/4.md
