### ISSUE TITLE
add sublevel aperture laboratories

### ISSUE THREAD

**Issue by Amalgamatte** [c-128/TheBackroomsExperiment#7]
![image](https://user-images.githubusercontent.com/108957198/228829232-e1b2fe3f-e3b6-40c3-b11e-9f789983f8c3.png)

![image](https://user-images.githubusercontent.com/108957198/228830578-9966dbf1-caaa-4405-921e-e25a4b2f6c65.png)

you can enter this sublevel from sublevel fun by the right slide exit

**Comment by c-128** [comment]
Done https://github.com/c-128/TheBackroomsExperiment/blob/master/wiki/sublevels/5.md
